### PR TITLE
Use flask_* instead of deprecated flask.ext.*

### PR DESCRIPTION
**Pull request by jeffwidman**
Details: https://github.com/mitsuhiko/flask/issues/1135

### CODE REVIEW

**Comment by rpicard** [comment]
I haven't been keeping up on these changes. To be clear, is this backwards compatible with extensions that might not have updated anything?

**Comment by jeffwidman** [comment]
Not sure if you saw it, but this gives more background: https://github.com/mitsuhiko/flask/issues/1135#issuecomment-61860862

Any extensions that aren't compatible will likely several years old at this point.

**Comment by rpicard** [comment]
Good enough for me.

**Comment by rpicard** [comment]
I should probably redeploy again soon. There are a bunch of changes that haven't made it to the live site yet.

**Pull request merged**
